export const MUTATE_SHOW_ERROR_NOTIFICATION = 'session/MUTATE_SHOW_ERROR_NOTIFICATION'
export const MUTATE_SHOW_USER_MODAL = 'session/MUTATE_SHOW_USER_MODAL'
export const GET_SESSION_STATE = 'session/STATE'

export default {
  MUTATE_SHOW_ERROR_NOTIFICATION,
  MUTATE_SHOW_USER_MODAL,
  GET_SESSION_STATE
}
